### ISSUE TITLE
Service selectors do not get read into k8s

### ISSUE THREAD

**Issue by badloop** [opencord/helm-charts#1]
FYI, not sure if its a kubernetes bug or what, but the selector block in the service definitions is not being read into kubernetes.  You need to move it above the service port definition like so:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sdnc.fullname" . }}-debugger
  labels:
    app: {{ template "sdnc.name" . }}
    chart: {{ template "sdnc.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.services.debuggerServiceType }}
  selector:
    app: {{ template "sdnc.name" . }}
    release: {{ .Release.Name }}
  ports:
  - name: debugger
{{ toYaml .Values.services.debugger | indent 4 }}
```

Possibly an issue with the toYaml function?
